name: documentation

on: [push]
  #pull_request:
  #  branches: [documentation]
  #push:
  #  branches: [documentation]


jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: "-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,C1B864F7FF5337E139B0C5E7BCA0206E

Wq1dJeCc4UEdUtwjAe5gT7LWJp+VwhMbunqPmrzQnvOUVkKh1S/fUVj5DHoUQJwv
PUk5h7OLkUvX83uy6skRMIiD8IAF4bjGI2JGI75Fxr/Rk2PTaU45mKaFpaIeXgWB
xoVUyHa1meGmvnbbzwtaCTat6re33OfBIBiw5thPKVb1Qku5UBnuX/e0lCY/Wibk
H/mlWwAU5O02NYAgLmnsgk1jkQIXrGEY0dpVR21F+1SwMCJ1Smpsdq1WI07d2y75
Nv3DUT7yndl6TndTmXxcVVoAwA1c6LJdQHHiPETCz9ZSW15pKDSv+Ck7Fyr93f2L
Yz+W9yzWPd6zHbTmRTjdgZothNXo42LE+ilw21nV0OtlrQyrKMva3z3NN1IL/79j
Ga+qntxo9jVRq/VJ9C+uLncRcU9UKbSyDSVta767RVkHtor4h3FM8+pQt+F2qhZU
YNRXeMqTOXEHgIvG1HChWV1XRoREQHKajPLjLRVw6KMbd2Aa1W9GuzN/olfFMBAK
RKNISRIutsjhrnr5tWY4hnjD2OTpKjXyY/jV4lx3j9OdCbb1FYCzS/OisdWvIRrQ
W0DqURoDo9zj76cFDAOo7RTG5/LZPxtYC44QVuTbzIuWS5DGn7PqOY+87LbfEgP/
oR/GN7xBDKjvYB425UGU+pWCWUEG25E8+iHfCoXZyzHs9enAspUWtnbhzWmyO05G
PRAIMoAA1iVljYMOHmtJvPz4nIAufJkb2Io/QBQkF7h75gnBp4JxFrcUrLaL5mdQ
RZpmv/qV08PnNV+pTgInQnhp3ElcChE4wPE/drZMyitYUwVwtxs4z/49OIq4FJdu
mFkMBlY87r+EcXCLyADhonz9bT9rSP+VEMhrSs4IAMkZHVXcL3TAJ7gKaGxQBdGG
KIFjw+yVh3R18MlcgMf+1/YB9IfsnHydt62N9op2T0AxyQgWbCQEbDL16B5vT5ff
mbGvArDZmNJCDsicQr8qFuZwJpuQlSXAaEXhZYN2NEXEaFLhwoBpryCfI+HvluJ9
/lxK4sbSSLlUIA40QVKAKGTJNw7PW9d5h7e7dlGwPP6pibvzil7wT+E/i2I7VboG
HwK3GJKP1Ft+AAJj4U8pwX+l70lS6MqdTfYulfBehkJmaHgnVnjgpmwW2fGUfze+
dKKpNvUj2QDdzoORpDDzR8i+YEYKEhLnHaEDnGzHAqfIq08SqjdFhTQmR/MbQJHD
PyZGdlCL0SiNIZ4Ca58HBz1FOzWrRSqh0Rj47uw11cpu9lrPiR+0FqEInEPUWHAY
k76s2Rzsa8GoXO64n+kbxhi1090v8zM3olzHYkDnPL++gT3c+uDdeMNdDtXP+4LV
toNrILyRCvJrlM8eXE2IE4sclm8CwJMFzf7MIfwOlX+HOQUxGen8ncxaBBtE5a6L
QjhJr783ngz1zwjycio2cQHJTaiAAzwVmFsGOf4hfqM0k2+xj77cbml7SaUaXIR7
Wofv5LiWpy6LCYdpJjmO5qBS0i/bHjkV/x874obsCu82NoUAWOZdf7PHrhgSWtRG
lqT51JUCyXZ7OWvmrb3dt4Uf6k1H5IQB6qYcQejcqlpt19piS8k/b498EdQYg4qJ
-----END RSA PRIVATE KEY-----
"
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: fabianastudillo
        run: |
          git config --global user.email "fabian.astudillo.salinas@gmail.com"
          git config --global user.name "Fabian Astudillo"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run deploy
