# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ documentation ]
  pull_request:
    branches: [ documentation ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      # Runs a set of commands using the runners shell
      - name: Relase to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: fabianastudillo
        run: |
          echo Installing
          yarn install
          echo Building
          yarn build
          git config --global user.email "fabian.astudillo.salinas@gmail.com"
          git config --global user.name "fabianastudillo"
          echo Deploying
          USE_SSH=true GIT_USER=fabianastudillo yarn deploy
          echo Finish deploying
